### ISSUE TITLE
건의

### ISSUE THREAD

**Issue by Bainble0211-6109** [Tim232/Logger#1]
![image](https://user-images.githubusercontent.com/61723993/97779583-534b9600-1bc2-11eb-9081-ef671926c56a.png)
이거 다 만들어주세여

**Comment by Tim232** [comment]
님이 만들어서 pull request하세요 ㅋㅋㅋ 왜 코드를 달라고해요.... 오픈소스가 뭔지 몰라여..?
업뎃은 제가 나중에 시간날때 차근차근할겁니다
